apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
  labels:
    name: backend-service
    app: todo-app
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30004
  selector:
    tier: backend
    app: todo-app
