apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    tier: backend
    app: todo-app
spec:
    replicas: 1
    selector:
      matchLabels:
        tier: backend
        app: todo-app
    template:
      metadata:
        labels:
          tier: backend
          app: todo-app
      spec:
        containers:
        - name: backend
          image: vezuwio/todoapp:1.1
          ports:
          - containerPort: 8080
